version: '3.8'

services:
  mysql:
    container_name: ess-mysql-dev
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ess
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "32574:32574"
    networks:
      - service-network
    restart: always
    security_opt:
      - seccomp:unconfined

networks:
  service-network:
    driver: bridge
